repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: tag-app-delivery

  # A short description of the repository that will show up on GitHub
  description: 📨🚚CNCF App Delivery TAG

  # A URL with more information about the repository
  homepage: https://cncf.io/projects
  
  # Collaborators: give specific users access to this repository.
  # see /governance/roles.md for details on write access policy
  # note that the permissions below may provide wider access than needed for
  # a specific role, and we trust these individuals to act according to their
  # role. If there are questions, please contact one of the chairs.
collaborators:
  # TOC Liasons (all have admin access)
  - username: kgamanji
    permission: admin

  - username: justincormack
    permission: admin

  # TAG Chairs (all have admin access)
  - username: AloisReitbauer
    permission: admin

  - username: thschue
    permission: admin
    
  - username: joshgav
    permission: admin

  # Tech Leads (all have maintain access)
  - username: AlexsJones
    permission: maintain

  - username: lianmakesthings
    permission: maintain

  # GitOps WG Chairs (all have push access)
  - username: todaywasawesome
    permission: push

  - username: scottrigby
    permission: push

  - username: chris-short
    permission: push

  # Platforms WG Chairs (all have push access)
  - username: roberthstrand
    permission: push

  - username: abangser
    permission: push

  # Artifacts WG Chairs (all have push access)
  - username: afflom
    permission: push
  - username: rchincha
    permission: push

    
